services:
  - type: web
    name: dab-notifier
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app -b 0.0.0.0:10000"
    envVars:
      - key: PORT
        value: "10000"
